# Characteristics
char_names <- tibble::tribble(
  ~Characteristic, ~name,
  "age", "Age, years, mean (SD)",
  "bmi", "Body-mass index, kg/m2",
  "sbp", "Systolic blood pressure, mm Hg",
  "egfr", "Estimated GFR, mL/min/1.73m2",
  "k", "Serum potassium, mmol/L",
  "bnp", "B-type natriuretic peptide, pg/mL",
  "nt_pro_bnp", "N-terminal pro B-type natriuretic peptide, pg/mL",
  "bmi_na", "Missing BMI",
  "sbp_na", "Missing SBP",
  "egfr_na", "Missing eGFR",
  "k_na", "Missing potassium",
  "bnp_na", "Missing BNP",
  "nt_pro_bnp_na", "Missing NT-proBNP",
  "sex", "Sex, no. (%)",
  "ethnic", "Ethnicity, no. (%)",
  "smok_fct", "Smoking status, no. (%)",
  "imd_fct", "Socioeconomic status quintile, no. (%)",
  "nyha_fct", "NYHA class, no. (%)",
  "new_hf", "New onset heart failure, no. (%)",
  "hcv19", "Prior COVID-19 diagnosis, no. (%)",
  "care_home", "History of discharge to care home, no. (%)",
  "tar", "Time at risk, years, median (IQR)",
  "BETABLOCK_6mo_after", "  Beta blocker",
  "ACEI_6mo_after", "  ACE inhibitor",
  "ARB_6mo_after", "  ARB",
  "ARNI_6mo_after", "  ARNI",
  "RAS_6mo_after", "  ACE inhibitor/ARB/ARNI",
  "MRA_6mo_after", "  MRA", 
  "DIURETIC_6mo_after", "  Loop diuretic",
  "SGLT2I_6mo_after", "  SGLT2 inhibitor"
)

# Comorbidities
comorb_names <- tibble::tribble(
  ~Characteristic, ~name,
  "prior_hosp", "Prior hospitalisations, total, median (IQR)",
  "prior_hosp_1yr", "Prior hospitalisations, within year of index date, median (IQR)",
  "prior_hosp_peryr", "Prior hospitalisations, per year, median (IQR)",
  "prior_gp", "Prior GP visits, total, median (IQR)",
  "prior_gp_1yr", "Prior GP visits, within year of index date, median (IQR)",
  "prior_gp_peryr", "Prior GP visits, per year, median (IQR)",
  "comorb_fct", "Number of comorbidities, no. (%)",
  "hdb", "  Diabetes",
  "hckd", "  Chronic kidney disease",
  "hobes", "  Obesity",
  "hlivd", "  Liver disease",
  "hcanc", "  Cancer",
  "hdem", "  Dementia",
  "hdep", "  Depression",
  "host", "  Osteoarthritis",
  "hthy", "  Thyroid disease",
  "hasthm", "  Asthma",
  "hcopd", "  Chronic obstructive pulmonary disease",
  "haf", "  Atrial fibrillation and flutter",
  "harryth", "  Atrial fibrillation and other arrhythmias",
  "hautoimmune", "  Autoimmune disease",
  "hhtn", "  Hypertension",
  "hvalvhd", "  Valvular heart disease",
  "hihd", "  Ischaemic heart disease",
  "hpad", "  Peripheral arterial disease",
  "hstk", "  Stroke",
  "hanae", "  Anaemia"
)
